# Application port.
server:
  port: 8080

# Application name.
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
  main:
    web-application-type: reactive

# Registers Gateway Application with Eureka.
eureka:
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka