spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - "GET"
              - "POST"
            allowed-headers:
              - "Content-Type"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: database
          uri: http://localhost:9000
          predicates:
            - Path= /database/**
          filters:
            - StripPrefix=1 # /database/all-movies -> /all-movies

        - id: timer
          uri: http://localhost:9001
          predicates:
            - Path= /timer/**
          filters:
            - StripPrefix=1 # ...

        - id: movies
          uri: http://localhost:9002
          predicates:
            - Path= /movies/**
          filters:
            - StripPrefix=1 # ...

        - id: sequentialloop
          uri: http://localhost:9100
          predicates:
            - Path= /sequentialloop/**
          filters:
            - StripPrefix=1 # ...

        - id: sequentialstream
          uri: http://localhost:9101
          predicates:
            - Path= /sequentialstream/**
          filters:
            - StripPrefix=1 # ...

        - id: parallelstream
          uri: http://localhost:9102
          predicates:
            - Path= /parallelstream/**
          filters:
            - StripPrefix=1 # ...

        - id: completablefuture
          uri: http://localhost:9103
          predicates:
            - Path= /completablefuture/**
          filters:
            - StripPrefix=1 # ...

        - id: concurrentflux
          uri: http://localhost:9104
          predicates:
            - Path= /concurrentflux/**
          filters:
            - StripPrefix=1 # ...

        - id: parallelflux
          uri: http://localhost:9105
          predicates:
            - Path= /parallelflux/**
          filters:
            - StripPrefix=1 # ...

        - id: structuredconcurrency
          uri: http://localhost:9106
          predicates:
            - Path= /structuredconcurrency/**
          filters:
            - StripPrefix=1 # ...

        - id: executorservice
          uri: http://localhost:9107
          predicates:
            - Path= /executorservice/**
          filters:
            - StripPrefix=1 # ...

        - id: executorcompletionservice
          uri: http://localhost:9108
          predicates:
            - Path= /executorcompletionservice/**
          filters:
            - StripPrefix=1 # ...
                
