# Application port.
server:
  port: 8080

# Application name.
spring:
  profiles:
    active: path
  application:
    name: gateway
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.web: DEBUG

# Registers Gateway Application with Eureka.
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka